name: C CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the image for cross-compatibility
      run:  docker buildx build --platform linux/amd64,linux/arm64 -t test/helloworld:latest .
    # - name: Build the docker image
    #   run: docker build -t test/helloworld:latest .
    - name: Run the docker image with exit command
      run: echo "exit" | docker run --rm -i test/helloworld:latest
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    
    - name: Tag the docker for docker hub
      run: docker tag test/helloworld carbonatedwaterr/my-own-cli:1.0
    - name: Push the docker to registry
      run: docker push carbonatedwaterr/my-own-cli:latest